<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\VeluriyamLib\VeluriyamLib.csproj" />
	</ItemGroup>

	<!-- References -->

</Project>